language: bash
services:
  - docker
branches:
  only:
    - master
script:
  # .net core 3.1 for amd64
  - docker pull mcr.microsoft.com/dotnet/core/aspnet:3.1
  - docker pull mcr.microsoft.com/dotnet/core/sdk:3.1

after_success:
  - echo $docker_password | docker login registry.cn-hangzhou.aliyuncs.com --username=$docker_username --password-stdin

  # .net core 3.1 for amd64
  - docker tag mcr.microsoft.com/dotnet/core/aspnet:3.1 registry.cn-hangzhou.aliyuncs.com/csharp/aspnet:3.1
  - docker tag mcr.microsoft.com/dotnet/core/sdk:3.1 registry.cn-hangzhou.aliyuncs.com/csharp/sdk:3.1

  # .net core 3.1 for amd64
  - docker push registry.cn-hangzhou.aliyuncs.com/csharp/aspnet:3.1
  - docker push registry.cn-hangzhou.aliyuncs.com/csharp/sdk:3.1
