language: bash
services:
  - docker
branches:
  only:
    - master
script:
  - docker pull mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim-arm32v7
  - docker pull mcr.microsoft.com/dotnet/core/aspnet:3.1

  - docker pull mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm32v7
  - docker pull mcr.microsoft.com/dotnet/core/sdk:3.1

after_success:
  - docker login --username=$docker_username --password=$docker_password registry.cn-hangzhou.aliyuncs.com

  - docker tag mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim-arm32v7 registry.cn-hangzhou.aliyuncs.com/soarch/aspnetcore:3.1-arm
  - docker tag mcr.microsoft.com/dotnet/core/aspnet:3.1 registry.cn-hangzhou.aliyuncs.com/soarch/aspnetcore:3.1

  - docker tag mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm32v7 registry.cn-hangzhou.aliyuncs.com/soarch/netcoresdk:3.1-arm
  - docker tag mcr.microsoft.com/dotnet/core/sdk:3.1 registry.cn-hangzhou.aliyuncs.com/soarch/netcoresdk:3.1

  - docker push registry.cn-hangzhou.aliyuncs.com/soarch/aspnetcore:3.1-arm
  - docker push registry.cn-hangzhou.aliyuncs.com/soarch/aspnetcore:3.1

  - docker push registry.cn-hangzhou.aliyuncs.com/soarch/netcoresdk:3.1-arm
  - docker push registry.cn-hangzhou.aliyuncs.com/soarch/netcoresdk:3.1
